### ISSUE TITLE
Error in Readme

### ISSUE THREAD

**Issue by julien-bouquet** [newtmitch/docker-sonar-scanner#16]
The readme contains an error 
This line need to be change 
`  -v $(pwd)/sonar-runner.properties:/root/sonar-scanner/conf/sonar-runner.properties \`
to 
`  -v $(pwd)/sonar-runner.properties:/root/sonar-scanner/conf/sonar-scanner.properties \`

With this change, the sonar-runner.properties will be taken with good properties

**Comment by newtmitch** [comment]
Fixed in PR #17 - thanks for the help there!
