### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by julien-bouquet** [newtmitch/docker-sonar-scanner#18]
You can add in readme a description about use sonar-scanner without a local sonarQube. So --link sonarqube become useless in run of docker sonar scanner

**Comment by newtmitch** [comment]
Thanks for the note @julien-bouquet - I'm not familiar enough with Sonar Scanner to understand the value of running without Qube. Is that something people would do normally?

**Comment by julien-bouquet** [comment]
I'm not familar too with Sonar Scanner. But you can start container from everywhere with a server sonar not locally. In my case, i want start the container sonar scanner in process of Ci, by example jenkins, and my server sonar is not the same machine.

**Comment by newtmitch** [comment]
Ahh, got it. Fair enough, I can add a note to the README so that it's clear for those without more specific Docker knowledge on how `--link` works (which is the deprecated approach anyway, now that Docker uses virtual networks as the preferred approach, but I digress for now).

Thanks
