### ISSUE TITLE
Scanner properties overrides server settings

### ISSUE THREAD

**Issue by theoutsider24** [newtmitch/docker-sonar-scanner#25]
The line to exclude node modules from the scan ("sonar.exclusions=**/node_modules/**/*") means that server-side configuration of ignored files will never be used since there's an existing scanner-level property

**Comment by newtmitch** [comment]
Good to know. I'll update the README to make that fact clear.

**Comment by newtmitch** [comment]
Ahh, nevermind, I see my comment in the README here:
> I've added this to the deafult sonar-runner.properties file, so remove that if you don't want it
there for some reason.

I'll take a look at that.

**Comment by newtmitch** [comment]
Fixed. Thanks for the report @theoutsider24
