### ISSUE TITLE
Incorrect workdir in 3.3.0 Alpine image

### ISSUE THREAD

**Issue by theoutsider24** [newtmitch/docker-sonar-scanner#28]
Dockerfile.sonarscanner-3.3.0-alpine still has "WORKDIR /root", should've been changed to "WORKDIR /src" as part of pull request #27

**Comment by newtmitch** [comment]
Thanks, good catch. I've updated the Dockerfile and am testing now. In fact, you bring up another good point, which is the `WORKDIR` variable should actually be `/usr/src` to match with the `projectBaseDir` setting in the `CMD` at the end. Thanks for picking that up.
