### ISSUE TITLE
Securing values in sonar-runner.properties

### ISSUE THREAD

**Issue by BasanthKomuroju** [newtmitch/docker-sonar-scanner#33]
Hello,

We would like to know if we can secure the sensitive information i.e., credentials and other values that we pass in sonar-runner.properties file. Could you please help?

Thanks.

**Comment by BasanthKomuroju** [comment]
We would run the sonar scan as a part of our Azure DevOps CI pipeline.

**Comment by newtmitch** [comment]
Sorry, I'm honestly not the best person to talk to about that. I'm a much lighter user of Sonar than most people here would be and wouldn't know how to suggest setting that up for Sonar itself. I'd imagine anything you could do with Sonar regularly you could do with the Docker version, but I wouldn't know how best to approach this particular challenge.

**Comment by DmitriyStoyanov** [comment]
@BasanthKomuroju, 
I guess you could use something like
sonar.login=${env.SONAR_LOGIN}
in your property file and add this variable SONAR_LOGIN in your env property
