### ISSUE TITLE
Switch to openjdk:8

### ISSUE THREAD

**Issue by vyo** [newtmitch/docker-sonar-scanner#4]
As per [Dockerhub (Java)](https://hub.docker.com/_/openjdk/) usage of the `java:x` images is discouraged:
```
DEPRECATED
This image is officially deprecated in favor of the openjdk image,
and will receive no further updates after 2016-12-31 (Dec 31, 2016).
Please adjust your usage accordingly.
```
It is recommended to switch to [OpenJDK](https://hub.docker.com/_/openjdk/) which should be pretty trivial.

**Comment by newtmitch** [comment]
Thanks for the update and the link, @vyo. Let me take a look at that. I agree, the switch should be trivial.

**Comment by newtmitch** [comment]
Updated link for java deprecation notice: https://hub.docker.com/_/java/

**Comment by newtmitch** [comment]
Unless I'm reading it wrong the `java:8` tag was already aliased to `openjdk:8` at the Dockerhub level, so I think it's been running with the same binary level as openjdk 8 anyway. Updating the Dockerfile to `openjdk:8` and running the build again didn't pull down any new Docker layers. Just a note for my/someone's future reference. :)

**Comment by vyo** [comment]
@newtmitch imho this just due to the image being built the same way and thus Docker's caching kicking in. I don't think they do any sort of aliasing.

**Comment by newtmitch** [comment]
You're right - they have a bunch of openjdk-8 tags in there but not the exact `openjdk:8` that I ended up using.
