### ISSUE TITLE
Provide way to use external elasticsearch instead of embedded one

### ISSUE THREAD

**Issue by arthurlogilab** [newtmitch/docker-sonar-scanner#40]
Hi ! 

We're trying to upgrade our sonarqube which is running on our kubernetes cluster to the latest version. With elasticsearch embedded (can't wait to see the new features!) it can't start (without further tweaking) because of the (documented) sysconf calls one should make. 

Is there any way to use an external elasticsearch ? (we have one running outside of our kubernetes cluster) ?

**Comment by newtmitch** [comment]
This seems like a question about Sonarqube itself, not the sonar scanner, is that correct?

**Comment by arthurlogilab** [comment]
You're right ! Wrong repo. Sorry for the noise, and while I'm at it : thanks for your work on packaging the scanner for docker !
