### ISSUE TITLE
Is this plugin support gitlab repository ?

### ISSUE THREAD

**Issue by gth7754125** [newtmitch/docker-sonar-scanner#41]
like the question above...Could it be used to other git repository like gitee or gitlab ?

**Comment by newtmitch** [comment]
Not sure what you're asking here. Sonar and Scanner themselves don't directly integrate with any git hosting service - they operate on a git repo on a local filesystem, regardless of where it's hosted. If you have a specific technical question or issue that you're having, please feel free to further elaborate.

**Comment by newtmitch** [comment]
Closing, not sure there's an issue here as much as a question.
